// Generated by jextract

package io.askimo.ui.voice.whispercpp;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class whisper_h extends whisper_h$shared {

    whisper_h() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup();

    private static class whisper_init_from_file_with_params {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            whisper_h.C_POINTER,
            whisper_h.C_POINTER,
            whisper_context_params.layout()
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("whisper_init_from_file_with_params");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct whisper_context *whisper_init_from_file_with_params(const char *path_model, struct whisper_context_params params)
     * }
     */
    public static FunctionDescriptor whisper_init_from_file_with_params$descriptor() {
        return whisper_init_from_file_with_params.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct whisper_context *whisper_init_from_file_with_params(const char *path_model, struct whisper_context_params params)
     * }
     */
    public static MethodHandle whisper_init_from_file_with_params$handle() {
        return whisper_init_from_file_with_params.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct whisper_context *whisper_init_from_file_with_params(const char *path_model, struct whisper_context_params params)
     * }
     */
    public static MemorySegment whisper_init_from_file_with_params$address() {
        return whisper_init_from_file_with_params.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct whisper_context *whisper_init_from_file_with_params(const char *path_model, struct whisper_context_params params)
     * }
     */
    public static MemorySegment whisper_init_from_file_with_params(MemorySegment path_model, MemorySegment params) {
        var mh$ = whisper_init_from_file_with_params.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("whisper_init_from_file_with_params", path_model, params);
            }
            return (MemorySegment)mh$.invokeExact(path_model, params);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class whisper_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            whisper_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("whisper_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void whisper_free(struct whisper_context *ctx)
     * }
     */
    public static FunctionDescriptor whisper_free$descriptor() {
        return whisper_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void whisper_free(struct whisper_context *ctx)
     * }
     */
    public static MethodHandle whisper_free$handle() {
        return whisper_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void whisper_free(struct whisper_context *ctx)
     * }
     */
    public static MemorySegment whisper_free$address() {
        return whisper_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void whisper_free(struct whisper_context *ctx)
     * }
     */
    public static void whisper_free(MemorySegment ctx) {
        var mh$ = whisper_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("whisper_free", ctx);
            }
            mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class whisper_print_system_info {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            whisper_h.C_POINTER    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("whisper_print_system_info");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *whisper_print_system_info()
     * }
     */
    public static FunctionDescriptor whisper_print_system_info$descriptor() {
        return whisper_print_system_info.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *whisper_print_system_info()
     * }
     */
    public static MethodHandle whisper_print_system_info$handle() {
        return whisper_print_system_info.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *whisper_print_system_info()
     * }
     */
    public static MemorySegment whisper_print_system_info$address() {
        return whisper_print_system_info.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *whisper_print_system_info()
     * }
     */
    public static MemorySegment whisper_print_system_info() {
        var mh$ = whisper_print_system_info.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("whisper_print_system_info");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int WHISPER_SAMPLING_GREEDY = (int)0L;
    /**
     * {@snippet lang=c :
     * enum whisper_sampling_strategy.WHISPER_SAMPLING_GREEDY = 0
     * }
     */
    public static int WHISPER_SAMPLING_GREEDY() {
        return WHISPER_SAMPLING_GREEDY;
    }

    private static class whisper_context_default_params {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            whisper_context_params.layout()    );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("whisper_context_default_params");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct whisper_context_params whisper_context_default_params()
     * }
     */
    public static FunctionDescriptor whisper_context_default_params$descriptor() {
        return whisper_context_default_params.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct whisper_context_params whisper_context_default_params()
     * }
     */
    public static MethodHandle whisper_context_default_params$handle() {
        return whisper_context_default_params.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct whisper_context_params whisper_context_default_params()
     * }
     */
    public static MemorySegment whisper_context_default_params$address() {
        return whisper_context_default_params.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct whisper_context_params whisper_context_default_params()
     * }
     */
    public static MemorySegment whisper_context_default_params(SegmentAllocator allocator) {
        var mh$ = whisper_context_default_params.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("whisper_context_default_params", allocator);
            }
            return (MemorySegment)mh$.invokeExact(allocator);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class whisper_full_default_params {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            whisper_full_params.layout(),
            whisper_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("whisper_full_default_params");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * struct whisper_full_params whisper_full_default_params(enum whisper_sampling_strategy strategy)
     * }
     */
    public static FunctionDescriptor whisper_full_default_params$descriptor() {
        return whisper_full_default_params.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * struct whisper_full_params whisper_full_default_params(enum whisper_sampling_strategy strategy)
     * }
     */
    public static MethodHandle whisper_full_default_params$handle() {
        return whisper_full_default_params.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * struct whisper_full_params whisper_full_default_params(enum whisper_sampling_strategy strategy)
     * }
     */
    public static MemorySegment whisper_full_default_params$address() {
        return whisper_full_default_params.ADDR;
    }

    /**
     * {@snippet lang=c :
     * struct whisper_full_params whisper_full_default_params(enum whisper_sampling_strategy strategy)
     * }
     */
    public static MemorySegment whisper_full_default_params(SegmentAllocator allocator, int strategy) {
        var mh$ = whisper_full_default_params.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("whisper_full_default_params", allocator, strategy);
            }
            return (MemorySegment)mh$.invokeExact(allocator, strategy);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class whisper_full {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            whisper_h.C_INT,
            whisper_h.C_POINTER,
            whisper_full_params.layout(),
            whisper_h.C_POINTER,
            whisper_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("whisper_full");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int whisper_full(struct whisper_context *ctx, struct whisper_full_params params, const float *samples, int n_samples)
     * }
     */
    public static FunctionDescriptor whisper_full$descriptor() {
        return whisper_full.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int whisper_full(struct whisper_context *ctx, struct whisper_full_params params, const float *samples, int n_samples)
     * }
     */
    public static MethodHandle whisper_full$handle() {
        return whisper_full.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int whisper_full(struct whisper_context *ctx, struct whisper_full_params params, const float *samples, int n_samples)
     * }
     */
    public static MemorySegment whisper_full$address() {
        return whisper_full.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int whisper_full(struct whisper_context *ctx, struct whisper_full_params params, const float *samples, int n_samples)
     * }
     */
    public static int whisper_full(MemorySegment ctx, MemorySegment params, MemorySegment samples, int n_samples) {
        var mh$ = whisper_full.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("whisper_full", ctx, params, samples, n_samples);
            }
            return (int)mh$.invokeExact(ctx, params, samples, n_samples);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class whisper_full_n_segments {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            whisper_h.C_INT,
            whisper_h.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("whisper_full_n_segments");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int whisper_full_n_segments(struct whisper_context *ctx)
     * }
     */
    public static FunctionDescriptor whisper_full_n_segments$descriptor() {
        return whisper_full_n_segments.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int whisper_full_n_segments(struct whisper_context *ctx)
     * }
     */
    public static MethodHandle whisper_full_n_segments$handle() {
        return whisper_full_n_segments.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int whisper_full_n_segments(struct whisper_context *ctx)
     * }
     */
    public static MemorySegment whisper_full_n_segments$address() {
        return whisper_full_n_segments.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int whisper_full_n_segments(struct whisper_context *ctx)
     * }
     */
    public static int whisper_full_n_segments(MemorySegment ctx) {
        var mh$ = whisper_full_n_segments.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("whisper_full_n_segments", ctx);
            }
            return (int)mh$.invokeExact(ctx);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class whisper_full_get_segment_text {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            whisper_h.C_POINTER,
            whisper_h.C_POINTER,
            whisper_h.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("whisper_full_get_segment_text");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *whisper_full_get_segment_text(struct whisper_context *ctx, int i_segment)
     * }
     */
    public static FunctionDescriptor whisper_full_get_segment_text$descriptor() {
        return whisper_full_get_segment_text.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *whisper_full_get_segment_text(struct whisper_context *ctx, int i_segment)
     * }
     */
    public static MethodHandle whisper_full_get_segment_text$handle() {
        return whisper_full_get_segment_text.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *whisper_full_get_segment_text(struct whisper_context *ctx, int i_segment)
     * }
     */
    public static MemorySegment whisper_full_get_segment_text$address() {
        return whisper_full_get_segment_text.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *whisper_full_get_segment_text(struct whisper_context *ctx, int i_segment)
     * }
     */
    public static MemorySegment whisper_full_get_segment_text(MemorySegment ctx, int i_segment) {
        var mh$ = whisper_full_get_segment_text.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("whisper_full_get_segment_text", ctx, i_segment);
            }
            return (MemorySegment)mh$.invokeExact(ctx, i_segment);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

